 const Form2InputList = ({ updateForm2, form2 }) => {
  return {
    nameInsuredInput: {
      onChange: updateForm2,
      name: "nameInsured",
      type: "text",
      value: form2.nameInsured,
      placeholder: "Name of Insured",
    },

    descriptionRiskInput: {
      onChange: updateForm2,
      name: "descriptionRisk",
      type: "text",
      value: form2.descriptionRisk,
      placeholder: "Description Risk",
    },

    coverageCodeInput: {
      onChange: updateForm2,
      name: "coverageCode",
      type: "select",
      value: form2.coverageCode,
      placeholder: "Coverage Code",
      options: [
         { label: "1000 Crime", value: "1000 Crime" },
  { label: "1001 Excess Crime", value: "1001 Excess Crime" },
  { label: "1002 Kidnap & Ransom", value: "1002 Kidnap & Ransom" },
  { label: "1010 Workplace Violence", value: "1010 Workplace Violence" },
  { label: "2000 Commercial Property - Basic Form", value: "2000 Commercial Property - Basic Form" },
  { label: "2001 Commercial Property - Special Form/All Risk", value: "2001 Commercial Property - Special Form/All Risk" },
  { label: "2002 Commercial Property - Multi-Peril", value: "2002 Commercial Property - Multi-Peril" },
  { label: "2003 Individual Insureds With Large Schedules Where Tiv >$500M", value: "2003 Individual Insureds With Large Schedules Where Tiv >$500M" },
  { label: "2010 Builders Risk - Commercial", value: "2010 Builders Risk - Commercial" },
  { label: "2020 Vacant Buildings - Commercial", value: "2020 Vacant Buildings - Commercial" },
  { label: "2030 Business Income/Interruption", value: "2030 Business Income/Interruption" },
  { label: "2031 Trade Name Restoration/Food Borne Illness", value: "2031 Trade Name Restoration/Food Borne Illness" },
  { label: "2040 Disaster Income Protection", value: "2040 Disaster Income Protection" },
  { label: "2100 Stand Alone Earthquake With Limits <=$10M - Commercial Property", value: "2100 Stand Alone Earthquake With Limits <=$10M - Commercial Property" },
  { label: "2110 Difference In Conditions With Limits <=$10M - Commercial Property", value: "2110 Difference In Conditions With Limits <=$10M - Commercial Property" },
  { label: "2120 Commercial Dic/Stand Alone Earthquake With Limits >$10M", value: "2120 Commercial Dic/Stand Alone Earthquake With Limits >$10M" },
  { label: "2130 Parametric Earthquake", value: "2130 Parametric Earthquake" },
  { label: "2200 Flood - Commercial", value: "2200 Flood - Commercial" },
  { label: "2201 Excess Flood - Commercial", value: "2201 Excess Flood - Commercial" },
  { label: "2202 Flood & Landslide - Commercial", value: "2202 Flood & Landslide - Commercial" },
  { label: "2203 Flood & Volcanic Eruption - Commercial", value: "2203 Flood & Volcanic Eruption - Commercial" },
  { label: "2210 Wind/Windstorm - Commercial", value: "2210 Wind/Windstorm - Commercial" },
  { label: "2230 Forced-Place Insurance", value: "2230 Forced-Place Insurance" },
  { label: "2240 Parametric Wildfire - Commercial", value: "2240 Parametric Wildfire - Commercial" },
  { label: "2300 Terrorism - Stand Alone", value: "2300 Terrorism - Stand Alone" },
  { label: "2301 Terrorism - Special Multi-Peril", value: "2301 Terrorism - Special Multi-Peril" },
  { label: "2400 Glass", value: "2400 Glass" },
  { label: "2401 Hay In The Open", value: "2401 Hay In The Open" },
  { label: "2402 Sawmills", value: "2402 Sawmills" },
  { label: "2403 Explosive Manufacturing/Sales/Storage", value: "2403 Explosive Manufacturing/Sales/Storage" },
  { label: "2404 Amusement Parks/Carnivals And Amusement Devices", value: "2404 Amusement Parks/Carnivals And Amusement Devices" },
  { label: "2600 Dwelling", value: "2600 Dwelling" },
  { label: "2610 Homeowners - Basic Form", value: "2610 Homeowners - Basic Form" },
  { label: "2611 Homeowners - Multi-Peril", value: "2611 Homeowners - Multi-Peril" },
  { label: "2620 Builders Risk - Personal", value: "2620 Builders Risk - Personal" },
  { label: "2630 Farmowners - Multi-Peril", value: "2630 Farmowners - Multi-Peril" },
  { label: "2640 Vacant Buildings - Personal", value: "2640 Vacant Buildings - Personal" },
  { label: "2700 Residential Earthquake", value: "2700 Residential Earthquake" },
  { label: "2710 Homeowners Earthquake/Excess Limits Or Deductible Buyback", value: "2710 Homeowners Earthquake/Excess Limits Or Deductible Buyback" },
  { label: "2800 Flood - Personal", value: "2800 Flood - Personal" },
  { label: "2801 Excess Flood - Personal", value: "2801 Excess Flood - Personal" },
  { label: "2802 Flood & Landslide - Personal", value: "2802 Flood & Landslide - Personal" },
  { label: "2803 Flood & Volcanic Eruption - Personal", value: "2803 Flood & Volcanic Eruption - Personal" },
  { label: "2810 Wind/Windstorm - Residential", value: "2810 Wind/Windstorm - Residential" },
  { label: "3000 Bonds", value: "3000 Bonds" },
  { label: "3001 Fidelity", value: "3001 Fidelity" },
  { label: "3100 Contract Liability", value: "3100 Contract Liability" },
  { label: "3101 Subguard", value: "3101 Subguard" },
  { label: "3102 Account Default", value: "3102 Account Default" },
  { label: "3103 Failure To Survive", value: "3103 Failure To Survive" },
  { label: "3104 Trade Credit", value: "3104 Trade Credit" },
  { label: "3105 Oocyte/Egg Donor/Ivf/Surrogate Contract", value: "3105 Oocyte/Egg Donor/Ivf/Surrogate Contract" },
  { label: "3106 Mortgage Insurance", value: "3106 Mortgage Insurance" },
  { label: "3110 Entertainment/Motion Pictures Contract", value: "3110 Entertainment/Motion Pictures Contract" },
  { label: "3111 Short Term Media/Entertainment Failure To Survive $5M+ (Film/Entertainment Productions)", value: "3111 Short Term Media/Entertainment Failure To Survive $5M+ (Film/Entertainment Productions)" },
  { label: "3120 Prize Indemnification (Excluding Hole-In-One Coverage)", value: "3120 Prize Indemnification (Excluding Hole-In-One Coverage)" },
  { label: "3121 Hole In One", value: "3121 Hole In One" },
  { label: "4000 Inland Marine", value: "4000 Inland Marine" },
  { label: "4001 Track Insurance", value: "4001 Track Insurance" },
  { label: "4010 Motor Truck Cargo", value: "4010 Motor Truck Cargo" },
  { label: "4011 Excess Motor Truck Cargo", value: "4011 Excess Motor Truck Cargo" },
  { label: "4020 Jeweler'S Block", value: "4020 Jeweler'S Block" },
  { label: "4030 Boiler & Machinery", value: "4030 Boiler & Machinery" },
  { label: "4100 Personal Articles Floater Broad", value: "4100 Personal Articles Floater Broad" },
  { label: "4101 Personal Articles Floaters Written On A Stand Alone Basis - Value Of The Schedule > $1M Or Contains A Single Item(S) >$100K", value: "4101 Personal Articles Floaters Written On A Stand Alone Basis - Value Of The Schedule > $1M Or Contains A Single Item(S) >$100K" },
  { label: "5000 General Liability", value: "5000 General Liability" },
  { label: "5010 Excess Liability (Incl. Umbrella)", value: "5010 Excess Liability (Incl. Umbrella)" },
  { label: "5011 Excess Liability Where Part Of Underlying Is Non-Admitted", value: "5011 Excess Liability Where Part Of Underlying Is Non-Admitted" },
  { label: "5012 Limits That Attach In Excess Of $150M", value: "5012 Limits That Attach In Excess Of $150M" },
  { label: "5013 Asset Protection", value: "5013 Asset Protection" },
  { label: "5020 Short Term Special Events (Excluding Hole-In-One)", value: "5020 Short Term Special Events (Excluding Hole-In-One)" },
  { label: "5021 Event Cancellation", value: "5021 Event Cancellation" },
  { label: "5100 Gen. Liability - Product Tampering", value: "5100 Gen. Liability - Product Tampering" },
  { label: "5101 Products/Completed Operations (Written On A Stand Alone Basis)", value: "5101 Products/Completed Operations (Written On A Stand Alone Basis)" },
  { label: "5102 Products Recall", value: "5102 Products Recall" },
  { label: "5103 Clinical And Similar Tests Of Pharmaceutical, Medical, Biological & Other Similar Products", value: "5103 Clinical And Similar Tests Of Pharmaceutical, Medical, Biological & Other Similar Products" },
  { label: "5200 Contractors Engaged In Construction Of New Tract Homes And/Or New Condominiums", value: "5200 Contractors Engaged In Construction Of New Tract Homes And/Or New Condominiums" },
  { label: "5201 Scaffold/Scaffold Contractor", value: "5201 Scaffold/Scaffold Contractor" },
  { label: "5202 Crane & Rigging Contractors", value: "5202 Crane & Rigging Contractors" },
  { label: "5203 Blasting Contractors", value: "5203 Blasting Contractors" },
  { label: "5204 Demolition Contractors", value: "5204 Demolition Contractors" },
  { label: "5205 Oilfield Contractors", value: "5205 Oilfield Contractors" },
  { label: "5300 Building Moving", value: "5300 Building Moving" },
  { label: "5301 Security Guard Services", value: "5301 Security Guard Services" },
  { label: "5302 Tattoo And Body Piercing Shops", value: "5302 Tattoo And Body Piercing Shops" },
  { label: "5303 Amusement Parks/Carnivals/Devices", value: "5303 Amusement Parks/Carnivals/Devices" },
  { label: "5304 Fireworks Displays", value: "5304 Fireworks Displays" },
  { label: "5305 Hot Air Balloon", value: "5305 Hot Air Balloon" },
  { label: "5306 Outfitters And Guides", value: "5306 Outfitters And Guides" },
  { label: "5307 Seasonal Or Mobile Fairs, Concessionaires, And Vendors, With Or Without Liquor Liability", value: "5307 Seasonal Or Mobile Fairs, Concessionaires, And Vendors, With Or Without Liquor Liability" },
  { label: "5308 Ambulance Services Including Professional Liability", value: "5308 Ambulance Services Including Professional Liability" },
  { label: "5309 Explosives Including Manufacturing/Sales/Storage", value: "5309 Explosives Including Manufacturing/Sales/Storage" },
  { label: "5400 Liquor Liability", value: "5400 Liquor Liability" },
  { label: "5401 Wildfire Liability", value: "5401 Wildfire Liability" },
  { label: "5402 Animal Liability", value: "5402 Animal Liability" },
  { label: "5410 Environmental Impairment Remediation And Pollution Liability", value: "5410 Environmental Impairment Remediation And Pollution Liability" },
  { label: "5500 Foster Family (Occurrence Based Only)", value: "5500 Foster Family (Occurrence Based Only)" },
  { label: "5915 Excess Liability - Cyber - Where Part Of The Underlying Is Non-Admitted", value: "5915 Excess Liability - Cyber - Where Part Of The Underlying Is Non-Admitted" },
  { label: "6000 Errors & Omissions", value: "6000 Errors & Omissions" },
  { label: "6001 Media Liability", value: "6001 Media Liability" },
  { label: "6010 Directors & Officers", value: "6010 Directors & Officers" },
  { label: "6020 Employment Practices Liability", value: "6020 Employment Practices Liability" },
  { label: "6021 Sexual Misconduct", value: "6021 Sexual Misconduct" },
  { label: "6030 Representations & Warranties", value: "6030 Representations & Warranties" },
  { label: "6031 Excess Representations & Warranties", value: "6031 Excess Representations & Warranties" },
  { label: "6040 Patent/Trademark/Copyright Infringement", value: "6040 Patent/Trademark/Copyright Infringement" },
  { label: "6100 Architects & Engineers/Condo Coverage Only", value: "6100 Architects & Engineers/Condo Coverage Only" },
  { label: "6101 Tattoo & Body Piercing Shops E&O", value: "6101 Tattoo & Body Piercing Shops E&O" },
  { label: "6200 Cyber Liability", value: "6200 Cyber Liability" },
  { label: "6201 Cyber Cargo", value: "6201 Cyber Cargo" },
  { label: "6202 Excess Cyber - Professional Liabilty/Errors & Omission", value: "6202 Excess Cyber - Professional Liabilty/Errors & Omission" },
  { label: "6210 Cyber Multi-Peril", value: "6210 Cyber Multi-Peril" },
  { label: "6300 Medical Malpractice", value: "6300 Medical Malpractice" },
  { label: "6301 Medical Malpractice - Hospitals", value: "6301 Medical Malpractice - Hospitals" },
  { label: "6310 Physician/Medical Group/Hospital Billing E&O", value: "6310 Physician/Medical Group/Hospital Billing E&O" },
  { label: "6400 Campaign Treasurers", value: "6400 Campaign Treasurers" },
  { label: "6401 Creditors' Committees", value: "6401 Creditors' Committees" },
  { label: "7000 Accident", value: "7000 Accident" },
  { label: "7001 Accident - Disability Income", value: "7001 Accident - Disability Income" },
  { label: "7002 Accident - Group Health Insurance", value: "7002 Accident - Group Health Insurance" },
  { label: "7003 Accident - Indiviudal Health Ins.", value: "7003 Accident - Indiviudal Health Ins." },
  { label: "7005 International Major Medical", value: "7005 International Major Medical" },
  { label: "7006 High Limits Disability", value: "7006 High Limits Disability" },
  { label: "7007 Bridge Plan", value: "7007 Bridge Plan" },
  { label: "8000 Auto Liability - Commercial", value: "8000 Auto Liability - Commercial" },
  { label: "8010 Auto Physical Damage - Commercial", value: "8010 Auto Physical Damage - Commercial" },
  { label: "8020 Combined Auto Liability & P.D. - Comm", value: "8020 Combined Auto Liability & P.D. - Comm" },
  { label: "8030 Garage Liability", value: "8030 Garage Liability" },
  { label: "8040 Combined Trucking Liability & P.D.", value: "8040 Combined Trucking Liability & P.D." },
  { label: "8100 Auto Liability - Private", value: "8100 Auto Liability - Private" },
  { label: "8101 Exotic/Classic/Antique Autos With A Value >100K", value: "8101 Exotic/Classic/Antique Autos With A Value >100K" },
  { label: "8110 Auto Physical Damage -Private", value: "8110 Auto Physical Damage -Private" },
  { label: "8120 Combined Auto Liability & P.D. - Private", value: "8120 Combined Auto Liability & P.D. - Private" },
  { label: "8200 Any Vessel/With A Max Speed > 55 Mph", value: "8200 Any Vessel/With A Max Speed > 55 Mph" },
  { label: "8201 All Vessels >30 Feet And Rated Max Speed Of 45 Mph", value: "8201 All Vessels >30 Feet And Rated Max Speed Of 45 Mph" },
  { label: "8300 Short Term Media/Entertainment Railroad Protective Liability (Film/Entertainment Productions)", value: "8300 Short Term Media/Entertainment Railroad Protective Liability (Film/Entertainment Productions)" },
  { label: "8400 Aviation Liability", value: "8400 Aviation Liability" },
  { label: "8401 Aviation Excess Liability", value: "8401 Aviation Excess Liability" },
  { label: "8402 Short Term Media/Entertainment Non-Owned Contingent Aircraft Liability (Film/Entertainment Productions)", value: "8402 Short Term Media/Entertainment Non-Owned Contingent Aircraft Liability (Film/Entertainment Productions)" },
  { label: "8500 Drone Third-Party Liability", value: "8500 Drone Third-Party Liability" },
  { label: "8501 Drone Physical Damage Or Loss", value: "8501 Drone Physical Damage Or Loss" },
  { label: "8502 Drone Commercial Third-Party Liability And Optional Physical Damage", value: "8502 Drone Commercial Third-Party Liability And Optional Physical Damage" },
  { label: "9000 Legal Expense Reimbursement", value: "9000 Legal Expense Reimbursement" },
  { label: "9001 Excess Workers Compensation", value: "9001 Excess Workers Compensation" },
  { label: "9003 Nuclear Risk", value: "9003 Nuclear Risk" },
  { label: "9010 Travel Insurance", value: "9010 Travel Insurance" },
  { label: "9020 Political Risks Including Expropriation, Confiscation, Unfair Calling", value: "9020 Political Risks Including Expropriation, Confiscation, Unfair Calling" },
  { label: "9200 Miscellaneous - All Other", value: "9200 Miscellaneous - All Other" },
  { label: "9201 Commercial Dic/Stand Alone Earthquake For Policies With Effective Date Prior To 10/25/2018", value: "9201 Commercial Dic/Stand Alone Earthquake For Policies With Effective Date Prior To 10/25/2018" },
  { label: "9999 Legacy", value: "9999 Legacy" },     
 ],
        },
  };
};

export default Form2InputList